config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages, :only => [:index]
  resources :links, :only => [:create, :new, :show]
  resources :comments, :only => [:create]
  resources :chats
  resources :votes

  root :to => "pages#index"
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  has_many :chat_messages

end

app/models/chatmessage.rb
class ChatMessage < ActiveRecord::Base
  belongs_to :chat
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  belongs_to :user

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :votes
  has_many :comments
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true

  # self.per_page = 10
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  has_many :comments
  has_many :votes
  has_many :chats
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  validates :user_id, :uniqueness => { :scope => :link_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController

  def create
    @comment = current_user.comments.create(comment_params2)
    redirect_to :back
  end

  def new
    @comment = Comment.new
  end

  def comment_params2
    params.requre(:comment).permit(:message)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
    @chats = Chat.order('id ASC')
    @chat = Chat.first_or_create
  end

  def create
    redirect_to :back
  end

  def show
    @chat = Chat.find(params[:id])
  end

  def update
    @chat = Chat.create(chat_params)
    redirect_to :back
  end

  def new
    @chat = Chat.new
  end

  def chat_params
    params.require(:chat).permit(:chat_message, :email)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :redirect_back_unless_logged_in

  def redirect_back_unless_logged_in
    redirect_to :back unless current_user.present?
  end

  def create
    @comment = current_user.comments.create(comment_params)
    redirect_to :back
  end

  # def create
  #   @comment = Comment.create(comment_params)
  #   respond_to do |format|
  #     if @comment.save
  #       format.html { redirect_to :back }
  #       format.json { render :json => @comment }
  #     else
  #       format.html { redirect_to :back }
  #       format.json { render :json => @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def comment_params
    params.require(:comment).permit(:message, :link_id)
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def show
    @link = Link.find(params[:id])
    @comment = Comment.new
    @comments = @link.comments
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { render :action => "show" }
        format.json { render :json => @link }
      else
        format.html { render :action => "new" }
        format.json { render :json => @link.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @users = User.order('created_at DESC')
    @links = Link.order('created_at DESC').page(1).per_page(100)
    # @links = Link.all.paginate(page: (page_params[:page] || 1)).order('created_at DESC')
  end

  # def page_params
  #   params.permit(:page)
  # end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :redirect_back_unless_logged_in

  def redirect_back_unless_logged_in
    redirect_to :back unless current_user.present?
  end

  def create
    @vote = current_user.votes.create(votes_params)
    redirect_to :back
  end

  def show
    @link = Link.find(params[:id])
  end

  def votes_params
    params.require(:vote).permit(:link_id, :up)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/Chat/index.html.erb
<%= "tell me howzit" %>

app/views/chats/index.html.erb
<% if !user_signed_in? %>
<%= "Please Sign-in to View" %>
<% end %>


<% if user_signed_in? %>

<p>
  <b>Chat</b>
  <ul>
    <% @chats.each do |c| %>
      <li><%= c.created_at %> |
          <%= c.email %> -->
          <%= c.chat_message %></li>
    <% end %>
  </ul>
</p>

<%= form_for(@chat) do |f| %>

  <div class="field">
    <%= f.label :chat_message %><br />
    <%= f.text_area :chat_message, :placeholder => "New Message" %>
    <%= f.hidden_field :email, :value => current_user.email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
<% end %>

<p>
  <%= link_to 'Homepage', pages_path %>
</p>

app/views/chats/show.html.erb
<%= 'howisit' %>

<%= form_for(@chat.chat_message.new) do |f| %>

  <div class="field">
    <%= f.label :chat_message %><br />
    <%= f.text_area :chat_message %>
    <%= f.hidden_field :user_id, :value => @chat.user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<p>
  <%= link_to 'Homepage', pages_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Farley's Homepage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%# user is logged in, show log out link %>
<% if current_user.present? %>
  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
<%# user is not logged in, show signup and login links %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path %> |
  <%= link_to 'Register Now!', new_user_registration_path %>
  <% end %>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<!-- <%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->

app/views/links/chat.html.erb
<% if user_signed_in? %>

  <%= form_for(@comment) do |f| %>

    <div class="field">
      <%= f.label :message %><br />
      <%= f.text_area :message, :placeholder => "Add a comment" %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<p>
  <b>Comments</b>
  <ul>
    <% @comments.each do |c| %>
      <li><%= c.message %></li>
    <% end %>
  </ul>
</p>
<% end %>

<p>
  <%= link_to 'Homepage', pages_path %>
</p>

app/views/links/comments.html.erb
<%= form_for(@comment) do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/create.html.erb
<%= "Howzit" %>

app/views/links/new.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url, :size => 30 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<p>
<%= link_to 'Homepage', pages_path %>

app/views/links/show.html.erb
<%= "Hey" %>

<p id="notice"><%= notice %></p>

<p>
    <b>Title:</b>
    <%= @link.title %>
</p>

<p>
    <b>URL:</b>
    <%= @link.url %> |
    <%= link_to "Link", @link.url %>
</p>

<% if user_signed_in? %>


  <%= form_for(@link.comments.new) do |f| %>

    <div class="field">
      <%= f.label :message %><br />
      <%= f.text_area :message, :placeholder => "Add a comment" %>
      <%= f.hidden_field :link_id, :value => @link.id %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<p>
  <b>Comments</b>
  <ul>
    <% @link.comments.each do |c| %>
      <li><%= c.message %></li>
    <% end %>
  </ul>
</p>
<% end %>



<p>
  <%= link_to 'Homepage', pages_path %>
</p>

app/views/pages/index.html.erb
<p> <%= link_to 'Facebook', 'http://facebook.com', :target => "_blank" %> |
<%= link_to 'Reddit', 'http://reddit.com', :target => "_blank" %> |
<%= link_to 'Schneems', 'http://www.schneems.com/ut-rails/', :target => "_blank" %> |
<%= link_to 'Bovada', 'http://bovada.lv', :target => "_blank" %> </p>

<h2>Farley's Homepage</h2>

<% if !user_signed_in? %>
  -Please Register and Sign in!
<% end %>

<% if user_signed_in? %>
**********************************************************
<h2>Welcome Everyone</h2>
<b>Howzit
<%= current_user.email %></b>!
<br>
<p>-everyone with an account is listed below<br>
    -BGAME and MIA homies<br>
    -please add links!<br>
    -click everything and make sure it works!

</p>
<ul>
  <% @users.each do |user| %>
  <li>  <%= user.email %> |
        <%= "Account Created: #{user.created_at.strftime("%m/%d/%y")}" %> </li>
  <% end %>
</ul>

**********************************************************
<% end %>


<p></p>

<b><%= link_to "Add a link", new_link_path %></b> |
<%= link_to "Chat", chats_path %>

<ul>
  <% @links.each do |link| %>
  <li>  <%= link_to "+", votes_path(:vote => {:link_id => link.id, :up => true}), :method => :post %>
        <%= link.votes.where(:up => true).count - link.votes.where(:up => false).count %>
        <%= link_to "-", votes_path(:vote => {:link_id => link.id, :up => false}), :method => :post %>
        <%= link_to link.title, link.url, :target => "_blank" %>
        <%= link.created_at.strftime("%m/%d/%y") %></li>
        <%= link_to 'comments', link_path(:id => link.id) %>
        <p> </p>
  <% end %>
</ul>

<!-- <%= will_paginate @links %> -->